FROM node:20

WORKDIR /app

COPY package*.json ./

RUN npm install -f

COPY . .

# Pasar variables en tiempo de build
ARG VITE_API_URL
ARG VITE_GITLAB_CLIENT_SECRET
ARG VITE_GITLAB_CLIENT_ID
ARG VITE_REDIRECT_URI

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_GITLAB_CLIENT_SECRET=$VITE_GITLAB_CLIENT_SECRET
ENV VITE_GITLAB_CLIENT_ID=$VITE_GITLAB_CLIENT_ID
ENV VITE_REDIRECT_URI=$VITE_REDIRECT_URI

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "preview"]
